default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: password

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: postgres
  password: password
  host: db
  pool: 5

test:
  <<: *default
  database: dbtest

production:
  url: <%= ENV['DATABASE_URL'] %>
